use strict;
use warnings;

my $mRNA = <<"_END_";
AUGCACCGGCCCCCCCGAGCAGGCGCGAAGACGUGAAUGGGGAAAAACAAACCGCAGGGCGCGGAGA
ACAGACCACCGGCCCGCGGACGCGAAAAGCAAAGGGAAAAGACGGGAUAAAUGGAGGGACCCGAAGC
AGCAGCGGAGGACGCCCCCAAGAAGCAAACGAAAUGAAUGGGCAGAAGCACAGACAGAACCACCCAG
UAGAUGAAGCGGGAGAAGAAGGCGCCAGGCCGGGACCAAGAAGAACCAACCAACAGCCCGACGUAGA
UGGGAGCGCCGCGCAAGCACCAAGGGCACAAGCGGGCCGCCCGACGCCGAGGGCCACCCCAGGAGCA
CGGACGCAGAGCAAGAUAAAUGAAAAAGGCGAAGGGACCGAGCACGUAGAUGACGGCCCAACCGGAG
CGAGACCAACACAAGGGGGGGGAGCCAAGGAAAAGGGCGAGCCCAGGGUGA
_END_

$mRNA =~ tr/\n//d; #deletes any character that matches (because of the \d tag)

my @matches = ($mRNA =~ /(AUG.*?(UAG|UAA|UGA))/g);

foreach(@matches){
	my $length = length($_);
	if($length > 3){
		print "$_ ($length)\n";
	}
}

#The way the regex expression is written
#it will also capture the stop codons because
#they are a nested group. So instead, check
#to see if captured match is greater than 3.
